spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: user-ms
          uri: lb://user-ms
          predicates:
            - Path=/users/**
        - id: terminal-ms
          uri: lb://terminal-ms
          predicates:
            - Path=/terminals/**
        - id: workitem-ms
          uri: lb://workitem-ms
          predicates:
            - Path=/workItems/**
        - id: vehicle-ms
          uri: lb://vehicle-ms
          predicates:
            - Path=/vehicles/**

server:
  port: 9093
eureka:
  instance:
    hostname: localhost